name: FREE_RDP_NEW_TOKEN
on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Install Ngrok
        run: |
          choco install ngrok -y
          Import-Module "$env:ProgramData\chocolatey\helpers\chocolateyInstaller.psm1"
          Update-SessionEnvironment

      - name: Configure Ngrok
        # Aapka naya token yahan update kar diya gaya hai
        run: ngrok config add-authtoken 37Iwu0EvVs1xbdOqdIAsS6X9KCn_6dtWT1a9XNM15aCMdG3PB

      - name: Enable Windows RDP
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

      - name: Start Tunnel and Display Address
        shell: pwsh
        run: |
          Start-Process ngrok -ArgumentList "tcp --region us 3389"
          Write-Host "Waiting for tunnel address..."
          Start-Sleep -Seconds 20
          # Ye command address ko seedha GitHub screen par print karegi
          $tunnels = Invoke-RestMethod http://localhost:4040/api/tunnels
          $address = $tunnels.tunnels[0].public_url
          Write-Host "----------------------------"
          Write-Host "YOUR RDP ADDRESS: $address"
          Write-Host "----------------------------"

      - name: Keep Alive
        run: Start-Sleep -Seconds 21600
